name: Run Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Allure reports
        run: rm -rf allure-reports/*

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Allure Commandline
        run: npm install allure-commandline --save-dev

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright Tests
        run: |
            cd $GITHUB_WORKSPACE 
            npx playwright test

      - name: Generate Allure report and send tg
        run: |
              cd $GITHUB_WORKSPACE
              npx allure generate allure-results --clean -o allure-reports
              allure generate allure-results
              chmod +x Telegramm.sh
              ./Telegramm.sh
        if: always()

      - name: Deploy Allure report to GitHub Pages
        id: deploy-to-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-reports
        if: always()

